# Generated by Django 3.2.11 on 2022-01-31 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listtodo', '0016_tweet_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cricket',
        ),
        migrations.DeleteModel(
            name='Cricketapp',
        ),
        migrations.DeleteModel(
            name='Todoapp',
        ),
        migrations.DeleteModel(
            name='Todoapps',
        ),
        migrations.AlterUniqueTogether(
            name='following',
            unique_together={('userid', 'followedby')},
        ),
    ]
